### ISSUE TITLE
Animation only seems to trigger on $state change 

### ISSUE THREAD

**Issue by austpere** [rpocklin/angular-scroll-animate#16]
I am using UI-Router and Angular-Material and cannot seem to get my animations to trigger on scroll. 

I could only get my animation on the top to initiate when I went to another state and then went back. When I went back to the state with the animation, the animation would trigger once. But once I scrolled away, the animation did not trigger itself again. The other animations lower on the page would also not display as well.

Do you know what could be happening that I am experiencing these issues?

**Comment by rpocklin** [comment]
If you can submit a plunkr I can take a look but if that is too hard i' recommend taking the example and copying those classes / logic until you work it out.

Apart from an actual transition, you also need to ensure the element is hidden when it is off the page, otherwise it won't animate in when it comes back into the viewport.

**Comment by austin4perezident** [comment]
Yes I had attempted to reproduce in a plunkr, but could not reproduce. I thought I attached a link to my website where the problem is occurring. [Here is a link](http://jaacmedia.com/) where you can see the issue. I have the animations on the front page.

I also found that if you resize the browser window, the text will appear and disappear. Not sure how to debug and find the underlying issue here.

**Comment by rpocklin** [comment]
Closed due to inactivity.
